---
- name: Clone of the official GIT repository
  git:
    repo: "{{ install_awx_git_repo }}"
    dest: "{{ install_awx_git_local_dir }}"
    version: "{{ install_awx_git_repo_version }}"

- name: Get AWX version available in GIT repository
  shell: "cat {{ install_awx_git_local_dir }}/VERSION"
  register: install_awx_current_version

- debug:
    msg: "WARNING: AWX Version {{ install_awx_current_version.stdout }} will be deployed. This version was not supported for this playbook. Supported version are {{ install_awx_supported_versions | join(', ') }}"
  when: install_awx_current_version.stdout not in install_awx_supported_versions
