---
- name: EPEL Repository Configuration
  yum: 
    name: epel-release

- name: Ensure necessary packages are installed
  yum: 
    name: "{{ install_awx_rpm_packages }}"
    state: latest

- name: Ensure that Python librairies for Docker are installed
  pip:
    name: "{{ install_awx_pip_packages }}"
    state: latest
